// PNW Ri3D: Team REDACTED
// Jon Grimm, Justin Grimm, Kevin Parsons
// 2015

// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveLeft1 = NULL;
SpeedController* RobotMap::driveLeft2 = NULL;
SpeedController* RobotMap::driveRight1 = NULL;
SpeedController* RobotMap::driveRight2 = NULL;
SpeedController* RobotMap::forkliftMotor1 = NULL;
SpeedController* RobotMap::forkliftMotor2 = NULL;
DoubleSolenoid* RobotMap::gripperSolenoid1 = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

Compressor* RobotMap::compressor1 = NULL;

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveLeft1 = new Talon(0);
	lw->AddActuator("Drive", "Left1", (Talon*) driveLeft1);
	
	driveLeft2 = new Talon(1);
	lw->AddActuator("Drive", "Left2", (Talon*) driveLeft2);
	
	driveRight1 = new Talon(2);
	lw->AddActuator("Drive", "Right1", (Talon*) driveRight1);
	
	driveRight2 = new Talon(3);
	lw->AddActuator("Drive", "Right2", (Talon*) driveRight2);
	
	forkliftMotor1 = new Talon(4);
	lw->AddActuator("Forklift", "Motor1", (Talon*) forkliftMotor1);
	
	forkliftMotor2 = new Talon(5);
	lw->AddActuator("Forklift", "Motor2", (Talon*) forkliftMotor2);
	
	gripperSolenoid1 = new DoubleSolenoid(0, 0, 1);      
	lw->AddActuator("Gripper", "Solenoid1", gripperSolenoid1);
	


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	compressor1 = new Compressor();
}
