// PNW Ri3D: Team REDACTED
// Jon Grimm, Justin Grimm, Kevin Parsons
// 2015

// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ForkliftMove.h"

ForkliftMove::ForkliftMove(float ForkSpeed, float Time) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::forklift);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	forkSpeed = ForkSpeed;
	time = Time;
}

// Called just before this Command runs the first time
void ForkliftMove::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void ForkliftMove::Execute() {
	Robot::forklift->motor1->Set(forkSpeed);
}

// Make this return true when this Command no longer needs to run execute()
bool ForkliftMove::IsFinished() {
	if (TimeSinceInitialized() > time)
				return true;
	return false;
}

// Called once after isFinished returns true
void ForkliftMove::End() {
	Robot::forklift->motor1->Set(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ForkliftMove::Interrupted() {
	End();
}
