// PNW Ri3D: Team REDACTED
// Jon Grimm, Justin Grimm, Kevin Parsons
// 2015

// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "GripperClose.h"
using namespace std;

GripperClose::GripperClose() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::gripper);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void GripperClose::Initialize() {
	Robot::gripper->solenoid1->Set(DoubleSolenoid::kForward);

	cout << "Gripper Close Init" << endl;
}

// Called repeatedly when this Command is scheduled to run
void GripperClose::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool GripperClose::IsFinished() {
	if (TimeSinceInitialized() > 0.5)
		return true;

	return false;
}

// Called once after isFinished returns true
void GripperClose::End() {
	Robot::gripper->solenoid1->Set(DoubleSolenoid::kOff);

	cout << "Gripper Close End" << endl;
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void GripperClose::Interrupted() {
	End();
}
